### ISSUE TITLE
Not able to use the default login

### ISSUE THREAD

**Issue by hectorjoey** [ppazos/cabolabs-ehrserver#1059] opened 2020-02-19 09:29 UTC
**Describe the bug**
I wanted to run the EHR server locally after then I couldn't log in

**Comment by ppazos** [comment] 2020-02-19 22:22
@hectorjoey what is the login you tried?

**Comment by hectorjoey** [comment] 2020-02-20 14:15
I have resolved the log in issue .. I found the credentials in the codebase.

**Comment by hectorjoey** [comment] 2020-02-20 14:17
I cant create a user or account . or perform any create operation. what do i do? thank you

**Comment by hectorjoey** [comment] 2020-02-20 14:42
also on the video on the login page, we have three fields which are username, password, and organization. while the one I have here just have a username and password; is that suppose to be a concern?
![ehr](https://user-images.githubusercontent.com/27903926/74945174-916ba580-53f7-11ea-89cf-17bbc4c30d58.PNG)

**Comment by ppazos** [comment] 2020-02-20 19:37
thanks @hectorjoey the videos you saw are for 1.x, the version you are testing is 2.1alpha

**Comment by hectorjoey** [comment] 2020-02-21 07:55
I cant create a user or account . or perform any create operation. what do i do? thank you

**Comment by ppazos** [comment] 2020-02-21 15:59
@hectorjoey you are testing a non-stable version ("alpha" means not stable) that is under heavy development, fork branch 1.5 for testing.

**Comment by ppazos** [comment] 2020-03-04 03:57
Closing since this is not a bug but related to usage questions.

**Closed by ppazos** 2020-03-04 03:57 UTC
Labels: bug, wontfix

**Comment by asdwtwty** [comment] 2020-07-10 00:00
I also have the same question after the ehrserver installed. I wonder what is the default username(email) and password, or how could i created them. thanks

**Comment by nr23730** [comment] 2020-09-07 13:45
To answer your question:

Email:
admin@cabolabs.com
Password: 
admin

I obtained the credentials from the source code.

**Comment by ppazos** [comment] 2020-09-07 17:24
@asdwtwty @nr23730 it's documented in the guide https://cloudehrserver.com/learn
